### ISSUE TITLE
Users can modify src of getSound manually

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#222]
In the spin-offs of Pamela's "What does Oh Noes Say?" I posted a program called experiments. It has a sound that plays on startup (apologies, it's just for testing not harassment.). You can basically say this:

soundVar.audio.src = "http://any.url.that/can/be/accessed.mp3";
Then play sounds through there.
Isn't too good that people can manually screw with the src.

**Comment by pamelafox** [comment]
That doesn't work for me on Chrome due to our Content-Security-Policy:
"Refused to load media from 'https://www.testedit.com/customsound.mp3/sad' because it violates the following Content Security Policy directive: "media-src *.kastatic.org www.khanacademy.org *.kasandbox.org"."

What browser does it work for you on?

**Comment by MikaalSky** [comment]
That link doesn't work. I haven't gotten an custom src to work yet but I'm working on it.

**Comment by pamelafox** [comment]
Okay, re-open if you can get it to work.
