### ISSUE TITLE
[Bug] Color becomes black in draw loop

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#235]
Reproduce by changing r here:

```
  // If you change foo.r by dragging the slider, the ellipse becomes black.
  var foo = {c:color(0, 0, 0), r:145};
  var draw = function() {
      background(255);
      fill(foo.c);
      ellipse(200, 200, foo.r, foo.r);
   };
```

**Comment by kevinb7** [comment]
I'll have a look at this one.

**Comment by kevinb7** [comment]
I've identified the issue.  It stems from this piece of code:
```
grabAll[global] = ((typeof value === "function" &&
                        !this.safeCalls[global]) ?
                    function() {
                        if (typeof fnCalls !== "undefined") {
                            fnCalls.push([global, arguments]);
                        }
                        return 0;
                    } :
                    value);
```
The problem is that we've set ```grabAll["color"]``` to return ```0```.  When run the code with the ```grabAll``` context to extract global variables we end up actually running ```grabAll["color"]``` which sets ```foo.c``` to ```0```.

I could try a band-aid of trying to clone values before they get overwritten and then try to restore them afterwards, but this is going to be quite awkward and may not be feasible in all cases.

I think a better strategy for dealing with this situation is to avoid using ```with``` and instead modify the code such that all references to global variables are rewritten to ```__context__.globalVar``` using an AST transform.  This avoids having to run the program once to capture globals before actually running it.
It also avoids having to pay the ```with``` tax, see http://jsperf.com/with-vs-direct-object-properties.

An AST based approach can also help with other inject related issues such as https://github.com/Khan/live-editor/issues/237 "[Bug] global variables initialized by function calls are not update when a draw function exists".

**Comment by kevinb7** [comment]
After doing some more investigation I noticed that if you remove color from the equation and just have a property ```r```, changing its value does not update the circle, but adding color into the picture allows the radius to update.  This bug is on master only and I believe has the same root cause as https://github.com/Khan/live-editor/issues/237.

**Comment by kevinb7** [comment]
After even more investigation, I found that there was an issue with ```setInterval``` not working correctly.  I traced this down to ```output_debugger_deps``` redefining ```setInterval``` incorrectly:

```
window.setInterval = function (callback, delay) {
  if (_isGeneratorFunction(callback)) {
    return originalSetInterval(function () {
      __schedule__(callback);
    }, delay);
  } else {
    return originalSetTimeout(callback, delay);  // this should be originalSetInterval
  }
};
```

The reason why the debugger had its own version of ```setInterval``` is because the default one doesn't work with generator functions.  I will fix this, but first I'm commenting out ```output_debugger_deps``` from output.html.  Then I'll update the index.html and output.html to conditionally load the debugger code as opposed to just conditionally enabling the debugger code.

I also figured out an easy fix for the ```color()``` issue... make it a "safeCall" which it is.  The reason why it doesn't show is because processing-js add a ```toString()``` method to ```color```.  Thus when we do ```String(color)``` to get the implementation as a string, it returns ```rgba(0,0,0,0)``` which has no return value.  It is safe because it doesn't call any other processing functions and has no side effects.

I'll send a PR tomorrow morning, but the hard work is done on this one.
