### ISSUE TITLE
Lagging/Crashing browser via Program.restart()

### ISSUE THREAD

**Issue by Gigabyte-Giant** [Khan/live-editor#280]
With the way the live-editor is set up, it is possible to lag (and even crash) a user's browser, by calling the `Program.restart()` function.

If you go to the [new program](https://www.khanacademy.org/computer-programming/new/pjs) page, and type `Program.restart()`, and nothing else, you can essentially break the canvas, and/or editor.

Although not needed, I did some experimentations, and figured out the simple reason why...

Any code that is in the global-scope (probably not the correct term), is executed when the program is started. So, if you were to type `println("Run")`, and nothing else, you would only see the message (*Run*), each time the canvas is initialized.

As you're aware, the `Program.restart()` function, restarts the canvas, as-if the user clicked the _Restart_ button.

Now, if you let that sit with you for a second, you'll realize what I'm about to say.

Invoking the `Program.restart()` function in the global-scope, will run it whenever the program *is (re)started*.

My proposal, is similar to the one used for `playSound`; Only allow users to invoke the restart function, from an event (i.e. on mouse click). (That being said, I would _*not*_ allow the restart function to be invoked from the `mouseMoved` function, as it's really pointless.)

Perhaps the best way to explain this, would be with a simple program. Open your browser console, and visit the following program. Once on the program, you may uncomment lines *4* and *5*.

https://www.khanacademy.org/computer-programming/issue-280-example/4555672970330112

Please note, your browser will most likely *not* lag or crash, however, you'll notice the editor does "break"... (Try selecting something in the editor on that program)

Best Regards,

Gigabyte Giant

**Comment by MikaalSky** [comment]
The thing is, until the random OOP edit error bug is fixed, this could mess up scripts that auto-fix the canvas for us.

**Comment by kevinb7** [comment]
@Gigabyte-Giant ```playSound``` can be invoked from the global scope.

@MikaalSky which random OOP edit error bug are you referring to?

**Comment by kevinb7** [comment]
We could insert code at the end of the main function that sets a hidden flag which could then be used to determine if we're running ```Program.restart()``` in the global scope or not.

**Comment by Gigabyte-Giant** [comment]
@kevinb7 Oh, well, I guess there isn't anything preventing that (invoking `playSound` from global scope), except for a simple guideline on the site...
Any sort of fix should be fine, I mean, it's not a big problem, but I do think it's something that should be considered.
Also, I'd just like to make it known, I *have only crashed the canvas and/or browser, once, and that's on a computer that's around 8 years old*.

**Comment by Gigabyte-Giant** [comment]
@MikaalSky Are you speaking of a "custom" script that _auto-fix_ the canvas? Or is there an actual script in the live-editor, that uses `Program.restart()` to fix OOP edit error problems?

**Comment by kevinb7** [comment]
@Gigabyte-Giant I'm a little embarrassed to say I don't know the guideline that you're referring to.  Can you post a link?

**Comment by MikaalSky** [comment]
@kevinb7 Yeah I'm referring to that.
Also, the guideline is this one
*Programs should only play sounds in response to user interaction - i.e., inside one of the mouse* or key* event handling functions. Programs should not play sounds immediately upon load, and should not loop sounds or play sounds everytime draw() is called. *

**Comment by kevinb7** [comment]
Thanks @MikaalSky.  It's funny, one of my test programs calls ```playSound``` in the global scope.  If you're using the number scrubber it can be super annoying so I can see why we'd want to discourage that practice.

Reading through the initial comment, I was thinking about preventing calls to ```Program.restart()``` from inside ```draw```.  There may be acceptable ways of calling it, e.g. putting the call inside an ```if``` statement with a predicate that's modified inside an event handler.  That got me thinking, maybe instead of trying to disable all uses of ```Program.restart()``` we change it's behaviour such that:
- we avoid blocking the main thread
- we provide user feedback so they can diagnose and fix issues with how they're using ```Program.restart()```

The first point should be easy enough: add a short timeout before restarting.  As for the second point, I was thinking maybe we could show the semi-transparent overlay or the throbber animation.

```Program.restart()``` is a quick way to reset state.  Users could reset most state by having some sort of ```setup``` or ```reset``` function that they can call.  The only thing that you can't seem to do is set a random seed.  Maybe we could add a ```randomSeed()``` function and encourage people to reset state themselves.

With regards to bugs like https://github.com/Khan/live-editor/issues/285, it would be awesome if we could fix them as opposed to pasting over them.  I had a bit of a brainwave which I'll post in that issue.

**Comment by Gigabyte-Giant** [comment]
I didn't even think about `Program.restart()` and the `draw` loop @kevinb7, good thinking!
How I typically use `Program.restart()`, is by throwing it into `mouseClicked`, `keyTyped`, or something similar. I think some of the following uses of `Program.restart()` (or a similar function/method), will be fine.
```javascript
mouseClicked = function() {
    Program.restart();
};
keyTyped = function() {
    Program.restart();
};
```
However, I don't think allowing `Program.restart()` inside of the `draw` loop will be ideal, even if it's in some form of an `if` statement, unless of course you could disallow things such as follows:
```javascript
var collaborator = "kevinb7";
draw = function() {
    if (collaborator === "kevinb7") {
        Program.restart();
    }
};```
...bad example, yes, however, hopefully you see what I'm saying there. :)

**Comment by Gigabyte-Giant** [comment]
Going to close this for now, if you ( @kevinb7 ) still feel this should be fixed, please reopen.

/close
