### ISSUE TITLE
Oh Noes pops up when there isn't an error sometimes.

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#285]
I type pretty fast and I find that Oh Noes keeps popping up after I even fix errors.

**Comment by pamelafox** [comment]
I have seen this issue as well but reliable replication  locally has been difficult. Here's a screencast that shows it: https://www.youtube.com/watch?v=fNVu7nf799I
And the code from that program:
http://pastebin.com/raw.php?i=UGRnRV2t
Unfortunately, I haven't managed to replicate it yet, following those steps.
If you are able to come up with a code/edit sequence/timing that replicates it somewhat reliably, please update this issue.

**Comment by MikaalSky** [comment]
Yeah, It's pretty hard to replicate but if you're working on a project you will come across it against once.

**Comment by kevinb7** [comment]
I think that the issue with this is that sometimes, if you're typing fast, or one of the workers happens to be slower than the other you can actually have the code you finished typing pass lint before the previous, incomplete version finishes linting.  This is because we have multiple web workers doing the linting, but there's nothing guaranteeing the order of the results.  There's a couple of ways that we can solve this:
- wait for one linter to finish before starting the next
  - benefits: saves resources
  - drawbacks: may reduce responsiveness, more changes to the code
- enumerate each lint run and ignore old lint results that arrive after new ones
  - benefits: maintains current responsiveness, should be fewer changes to the code
  - drawbacks: doesn't save resources

My vote would be for enumerating lint runs.

**Comment by MikaalSky** [comment]
How 'bout just waiting until a key hasn't been pressed for 10 seconds?

**Comment by kevinb7** [comment]
We run lint before run the program so waiting 10 seconds before doing so would be make the live-editor much less responsive than it is now.

**Comment by MikaalSky** [comment]
I think it's due to the linters overlapping. Like, you have one debugging the code, the other one from the previous one finishes with errors and the one still running finishes afterward with no bugs.
The canvas renders and errors appear.

**Comment by pamelafox** [comment]
We've had trouble replicating this recently, so I'm going to close this for now. Please re-open this issue if you've seen it recently, bonus points for another screencast. Thanks!

**Comment by pamelafox** [comment]
Just saw it today, re-opening.

**Comment by kevinb7** [comment]
I wrote some tests to verify that `PooledWorker` wasn't messing up and somehow providing lint results out of order.  It turns out we already have code in place to avoid this issue and it works.  Whenever we ask for a new worker, `PooledWorker` gives it a new id and those workers are used only once.  I tried a few different scenarios when testing: linting lots of code with error followed by short code with no errors, interleaving multiple runs, etc.  `PooledWorker` passed with flying colors.

I expanded my search a bit and found the ```phoneHome``` method with some comments that are quite apropos to the issue:
```
phoneHome: function() {
        // Our handling of errors is leaky.
        // In the old design errors were passed from function to function 
        // via arguments to callbacks. Recently I have added asynchronous sources 
        // of errors such as those from breaking out of an infinite loop.
        // These two different mechanisms mean that it's possible for errors to 
        // get lost, but it can't be fixed without rewriting how all of the callbacks
        // work. As a work around if we ever see an error, never erase it.
        // I made the judgement that rather than trying to merge the two it's ok if 
        // earlier errors cover newer ones, since once the user fixes the earlier errors 
        // the new ones will appear, meaning we never leave the user stuck wondering what to do. 
        // I expect that to be good enough compromise.
        if (this.lastSent && this.lastSent.errors && this.lastSent.errors.length) {
            this.results.errors = this.lastSent.errors;
        } 
        this.postParent({
            results: this.results
        });
        this.lastSent = JSON.parse(JSON.stringify(this.results));
    },
```
My first idea would be to create separate error queues for each mechanism, but I need to better understand how these two mechanism work before I attempt any sort of fix.

I'm going to throw this back on the pile until I have more dedicated time to look into it.

**Comment by pamelafox** [comment]
Students just ran into this at today's workshop, so it's still an issue. I'll see if I can get it in the support queue or in the project pipeline.

**Comment by kevinb7** [comment]
@pamelafox I'm on support next cycle so if it doesn't get dealt with in the next week I can dive into it then.

**Comment by kevinb7** [comment]
Implemented in https://github.com/Khan/live-editor/commit/06e8d399710ada9a8d0f1fd69470e8a235db6803.
