### ISSUE TITLE
getSound() doesn't work when loading strings from variables

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#302]
Due to the way we are loading sounds now, it does not work if people attempt to load the strings from variables, as done in https://www.khanacademy.org/computer-programming/balloon-popper-2/5419249456119808

The workaround is to put the string syntax in comments, since our getSound regex looks across the whole program.

A few thoughts:
- If we don't find the file in the cache (in getSound), we still attempt to load it, introducing a slight delay in programs like this
- We look for strings that match the filename syntax ("folder/file") or even specifically the exact filenames, and add that to the regex.
- We say this is expected behavior. 

var g_sounds = {};
/*
This comment means that it works. Try removing and reloading to see it not work.
getSound("rpg/coin-jingle");
getSound("retro/whistle1");
getSound("retro/jump2");
getSound("retro/hit2");
getSound("retro/whistle2");
getSound("retro/thruster-long");
*/
["rpg/coin-jingle", "retro/whistle1", "retro/jump2", "retro/hit2", "retro/whistle2", "retro/thruster-long"].forEach(function(el) {
    g_sounds[el] = getSound(el);
});

var mouseClicked = function() {
    playSound(g_sounds["retro/hit2"]);
};

**Comment by kevinb7** [comment]
Related to https://github.com/Khan/live-editor/issues/184.

> If we don't find the file in the cache (in getSound), we still attempt to load it, introducing a slight delay in programs like this

The way things right now getSound would return undefined because the load won't have a chance to complete.  We could store a placeholder object within resource cache that has a reference to the deferred.  Then we update ```playSound``` and ```drawImage``` so they know how to deal with deferreds.  I was thinking of the following semantics for when these functions receive a promise:
- resolved -> play it, draw it
- unresolved -> nop
- rejected -> error buddy

There will be some situations where an image isn't drawn (or a sound isn't played) on the first run.  This will definitely occur if the call to ```playSound``` or ```drawImage``` is in the same function body (or the main program body).

If all ```getSound``` and ```getImage``` calls were inside ```setup``` we could delay starting the run loop until all of the promises are resolved.

**Comment by kevinb7** [comment]
I had another idea about this.  Since we run the code once with everything stubbed out to check for invite loops, we could use those stubs to record the arguments passed to `getSound()` and `getImage()`.  We could then return these values from the worker and feed those into our resource loading code.  This would allow us to fix the issue without changing the semantics of these commands.

**Comment by kevinb7** [comment]
I thought about this a bit more about my suggestion about using stubs won't catch all edge cases.  @pamelafox I think your suggestion to "look for strings that match the filename syntax ("folder/file") or even specifically the exact filenames, and add that to the regex." will cover more edge cases and is simple to implement.  The only cases it won't cover are ones where people are intentionally try to have it not work, e.g. ```var sndName = "r" + "e" + "t" + "r" + "o" + "/" + "h" + "i" +"t" + "2"``` or something goofy like that.

**Comment by JavascriptFTW** [comment]
That wouldn't really work since people might do something like `var sounds = {retro:["boom1", "boom2", "hit1", "hit2", "coin", ...]};`, but it would still be an improvement

**Comment by kevinb7** [comment]
Fixed by https://github.com/Khan/live-editor/commit/e781a1ffce8adaabad0c1bfdaf1567e2929681c1.
