### ISSUE TITLE
[Feature] A tooltip that warns users about invalid URLs in hrefs

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#306]
We could have a tooltip that nudged users with bad hrefs,
like in the following HTML for a recent user report:
`  <li><a href="www.wcps.k12.va.us/lfk/">LFK</a></li>
        <li><a href="www.wcps.k12.va.us/hjb/">HJB</a></li>
        <li><a href="www.wcps.k12.va.us/rje/">RJE</a></li>`

I've seen many new HTMLers run into that in classes as well.

**Comment by jjwon** [comment]
Hey, is this still a relevant problem?  I'd love to give it a shot!

Just to be clear, it's not really that the urls are invalid (contain invalid characters as specified [here](http://tools.ietf.org/html/rfc3986#section-2)), but more that they don't point to the expected destination because they're missing the protocol?

**Comment by pamelafox** [comment]
Yeah, missing protocol is the main issue I've seen. Browsers tend to mask the protocol these days, which is part of why folks do it, I think.

**Comment by pamelafox** [comment]
I can close this now, yay!
