### ISSUE TITLE
PJS programs don't detect infinite loops inside draw(), which can freeze the browser

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#331]
Example 0: (Infinite loop)
https://gist.github.com/pamelafox/5b33d635393c92e391d2

Example 1: (Press the plus sign to freeze the browser - it might be inf or just long-running, haven't debugged)
https://gist.github.com/pamelafox/a0aaa11717508743f717

**Comment by kevinb7** [comment]
Yikes.  These are tough problems to detect.  Our current strategy of running the code to check for infinite loops doesn't work in the general case because some infinite loops may only occur after the program has run for an indefinite amount of time (Example 0) or may be trigger by some arbitrary user interaction (Example 1).  In order to prevent infinite loops in general we need to use the debugger that I was working on because it gives us the ability to interrupt execution at any point.  We could extend it to break if the ```draw``` method (or any method for that matter) takes longer than a certain threshold to complete.

**Comment by kevinb7** [comment]
Another possible solution is to adapt the infinite loop detector we use for the webpage environment for use in pjs.

**Comment by kevinb7** [comment]
Fixed by https://github.com/Khan/live-editor/commit/45cc5450965a077f8bf3642f7259b308ac4677ba.
