### ISSUE TITLE
Github-like System?

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#345]
Khan Academy programs already have "revisions" set up, so why not a git-like PR/Issue System? Just a suggestion that would be... Interesting to implement.

**Comment by kevinb7** [comment]
We've talked about doing something like this.  I have some thoughts in a email somewhere that I'll post here so that we can discuss it.

**Comment by kevinb7** [comment]
I think this would be quite beneficial for users because it gives them a safety net as they develop.  I think we should ignore branching though (at least to begin with) because with branching comes merging and merge conflicts and things become complicated.

**Comment by MikaalSky** [comment]
Yeah. At least a commit system, though, so if someone's code breaks, it's okay.

**Comment by Gigabyte-Giant** [comment]
+1 on the commit system idea. That'd be a lot better than having a different scratchpad for every version of the program.

**Comment by kevinb7** [comment]
@MikaalSky unfortunately, I don't think you'll be able to implement this because it will most likely require changes to the server which isn't open source.  

I'm going to close this because the feature is bigger than live-editor.  Let's continue the conversation here: https://khanacademy.zendesk.com/hc/communities/public/questions/202813360-Idea-diff-feature-button-for-spin-offs?locale=en-us.

**Comment by kevinb7** [comment]
Actually it might be better to post a separate idea.  The idea I linked to is for presenting some sort of side-by-side diff view which I think is different from what @MikaalSky has suggested here.
