### ISSUE TITLE
links to anchors have stopped working

### ISSUE THREAD

**Issue by kevinb7** [Khan/live-editor#390]
Introduced by https://github.com/Khan/live-editor/pull/378.  See https://www.khanacademy.org/computer-programming/internal-link/4582043175485440 for an example of this bug in action.  Thanks @SpongeJr for reporting this.  @jjwon do you have time to fix this?

**Comment by jjwon** [comment]
Sure, I'll submit a fix over the weekend.

I also realized something right now that's sort of an edge case: the regex that I added won't let you use relative links to access parts of the Khan Academy site.  See [this](https://www.khanacademy.org/computer-programming/internal-image-link/4744236575621120) for an example.  I can try to fix this edge case too, although it'd be kind of weird because it's a little contrary to the original fix.

**Comment by kevinb7** [comment]
Thanks.  We probably shouldn't be allowing relatively URLs like that anyways so don't worry about fixing that.

**Comment by MikaalSky** [comment]
Relative links will only link relatively to kasandbox so it would be a mostly pointless feature.

**Comment by pamelafox** [comment]
Hm. I think we could allow relative links so that folks who are working on HTML for other places can use relative links without getting Oh Noes Guy. I often write HTML in our editor and then paste it elsewhere, or I paste in HTML from elsewhere.

The big thing I wanted to help guide users with is the protocol-less URLs, like "google.com", as I saw that as a common mistake, likely caused by browsers masking protocols a lot. Those are never valid URLs.

**Comment by jjwon** [comment]
I feel like relative scripts/images/other things which will affect webpage appearance shouldn't be allowed since it won't render as it should.  I can see either argument for links, but it'll be a little confusing since relative urls aren't really valid and can be in a variety of formats.

For example, I can't quickly think of a good way to differentiate `<a href="about.html">link</a>` from `<a href="google.com">link</a>` except for trying to match TLDs against some master list.

**Comment by pamelafox** [comment]
That's fair. Can try it out with relative URLs not allowed.
