### ISSUE TITLE
Yoko Oh Noes does not  know that the rect function has eight parameters

### ISSUE THREAD

**Issue by lgto4** [Khan/live-editor#448]
Yoko Oh Noes needs to get up to speed wrt the Processing.js rect function.

`var rectangle = rect;
rectangle(200, 100, 150, 200, 0, 25, 0, 40);`

**Comment by MikaalSky** [comment]
True. Current workaround until this gets fixed to be more lenient:
rect(x,y,sX,sY,
r1,r2,r3,r4);

**Comment by kevinbarabash** [comment]
This should be a pretty easy issue to fix.  A person should be able to add additional optional params to the entry for `rect` in autosuggest.js.

**Comment by Gigabyte-Giant** [comment]
Just in case anyone is interested, and if I'm not terribly mistaken, the changes should go [here](https://github.com/Khan/live-editor/blob/master/js/ui/autosuggest-data.js#L21-L33).

**Comment by alexristich** [comment]
Hmm, this one's a little trickier than it first appeared. Adding tl, tr, br and bl params is possible, but it doesn't make sense to just tack them on as is. The current `rect` has `radius` as the fifth optional param, so adding these onto the back either means (a) having `radius` along with tl, tr, br and bl and having a clever way to ignore the fifth param, or (b) replacing `radius` with these more specific options, which allows for more control but less simplicity.

A final idea would be to come up with a way to, when a 6th param is entered, trigger a switch to another version of `rect` which has 8 params instead of 5 (thereby replacing `radius` in the tooltip with the four alternate options), but this might be more trouble than it's worth at the moment.

Thoughts?

**Comment by kevinbarabash** [comment]
@alexristich I think that we'd probably have to rework how we're storing params for overloaded functions.  Right now we only have the concept of optional params.  What I'd like to have is a list of function signatures that a user could cycle between when the autohint pops up.  I think that would address the issues that you've identified.

**Comment by alexristich** [comment]
Funny you mention that. When I first used the editor I wondered myself whether something like that might be better. I've been thinking about it for a bit here and, aside from any UI decisions, have a few questions of how this might best be accomplished. 

Presumably it would need to include the following:
1) An update to Oh Noes error checking logic so that it searches all the functions with a specified name
2) A way to suppress duplicate function names in the autohint popup (when typing a function name)
3) If possible, a way for the system to remember which function signature the user selected for a specific instance. Otherwise it might show the wrong tooltip if the user clicks away then back to a function where they specified a signature. This one seems tricky. Initially though, it could just show the functions stacked atop one another to at least be able to test it without tinkering with the UI.

Once I'm done with the tooltip fixes I mentioned in the other thread I'd be happy to lend a hand here if you think it's worth exploring further.

**Comment by MikaalSky** [comment]
Params: { "required" : ["params"], optionals: [["inside", "bundles"], ["for seperate situations"]] }

**Comment by Cis112233** [comment]
Adding another form of rect the EB looks at looks like the best way of doing this. The fastest way would be to have another rect command be added but that would end up being a pain. Adding an if statement in EB may work. Say if the params for rect are more than 5 use another message.

**Comment by Cis112233** [comment]
rect(200, 100, 150, 200, 0, 25);
Makes even more problems. That draws the rectangle with rounded edges but EB throws an error saying I put too many params

**Comment by kevinbarabash** [comment]
@Cis112233 you only need 5 params to draw rounded rects.

**Comment by DozenalFTW** [comment]
I think Cis112233 is trying to say that either
(a) the rectangle would have 0 round at tl and br, and 25 at tr and bl, OR
(b) the rectangle round would be an _elliptical_ arc, though the use of `0` implies not...

**Comment by kevinbarabash** [comment]
@DozenalFTW that makes sense.

**Comment by pamelafox** [comment]
Ethan's PR fixed this and is deployed, so I'm closing this issue. Thanks, Ethan!

**Comment by MatthiasSaihttam** [comment]
This was fixed by #661 for anyone curious (probably my future self).
