### ISSUE TITLE
this.textFont not working.

### ISSUE THREAD

**Issue by IndieKA** [Khan/live-editor#478]
This may have been posted by another user, so warn me if so.

If you use `this.textFont(createFont(font);` in a new program it does not work. 
Although this update was made about a year ago, I didn't see anyone report anything about it.

**Comment by Gigabyte-Giant** [comment]
`textFont` doesn't require the `this.` prefix. Removing it will allow you to invoke the function, as normal.

**Comment by IndieKA** [comment]
Okay, but multiple programs from 2 years ago (mainly by Brian French and Function97 use `this.` for `textFont`.

**Comment by pamelafox** [comment]
I can fix particular programs if you link to them and if they're popular
enough to warrant fixing them.

**Comment by IndieKA** [comment]
Popular enough? Hmm... 
https://www.khanacademy.org/computer-programming/buildprint-your-map-when-youre-done/1526458399
https://www.khanacademy.org/computer-programming/new-program/1690404430
https://www.khanacademy.org/computer-programming/house-of-puzzlement/1563254655
https://www.khanacademy.org/computer-programming/new-program/1778240331
https://www.khanacademy.org/computer-programming/spin-off-of-naval-assault-gameunfinished/1600940959
https://www.khanacademy.org/computer-programming/block-bonanza-wpause/1687284136

Although all of these are from @Function97, there are still a lot of programs out there w/the same thing. Especially old programs.

**Comment by Gigabyte-Giant** [comment]
Just a note @IndieKA, it might be helpful to provide some context when reporting potential issues in the future. I very well could've be mistaken in what I said-- so I'll gladly review the programs that you just posted.

 * https://www.khanacademy.org/computer-programming/buildprint-your-map-when-youre-done/1526458399
 * https://www.khanacademy.org/computer-programming/new-program/1690404430
 * https://www.khanacademy.org/computer-programming/spin-off-of-naval-assault-gameunfinished/1600940959

@pamelafox In the above programs, using `textFont`/`createFont` (instead of `this.textFont`/`this.createFont`), seems to work fine. Am I overlooking something?

In the following programs, however, switching to `textFont`/`createFont`, doesn't fix the problem...
 * https://www.khanacademy.org/computer-programming/house-of-puzzlement/1563254655
 * https://www.khanacademy.org/computer-programming/block-bonanza-wpause/1687284136

[This](https://www.khanacademy.org/computer-programming/new-program/1778240331) program doesn't appear to work, due to the fact that they're trying to use `externals`.

**Comment by pamelafox** [comment]
Yep. I've fixed the fixable ones.

**Comment by IndieKA** [comment]
@pamelafox What is wrong with using ctx??

**Comment by MikaalSky** [comment]
It's externals.

**Comment by kevinbarabash** [comment]
hmm... I didn't realize that this was working at one point.  @pamelafox thanks for fixing the fixable ones.
