### ISSUE TITLE
Open new window in jQuery

### ISSUE THREAD

**Issue by IndieKA** [Khan/live-editor#481]
Recently I found this program on someone's profile:
khanacademy.org/cs/p/4884341070757888
It shows that you can create new tabs using `jQuery`. You might want to feature that in the new course released a while back.

**Comment by pamelafox** [comment]
They're using window.open() there, which isn't jQuery specific, so it'd actually go inside the HTML/JS course if anywhere. I likely wouldn't teach it since it's not a commonly used thing in web development, as popups are generally annoying. We usually only use that when we're desperate for some reason.

For content suggestions, feel free to email compsci-feedback@khanacademy.org, I monitor that.
