### ISSUE TITLE
Incorrect font spacing with musical unicode characters 𝄠 𝅘𝅥𝅮

### ISSUE THREAD

**Issue by lafisrap** [Khan/live-editor#582]
If you copy the following into the live editor the cursor in lines 3 to 5 is not correctly positioned. It is also hard to edit the musical notes itself.
```
fill(141, 23, 209);
textSize(50);
text( "𝄠",160, 100);
text( "𝅘𝅥𝅮", 160, 200);
text( "𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮", 163, 300);

```
A list of musical notes you find here: http://unicode-table.com/en/blocks/musical-symbols/

**Comment by kevinbarabash** [comment]
What, that's pretty bad.  This is definitely an ace editor issue.  I think what's going on here is that the font being used by editor does not contain glyphs for these characters so the browser grabs the glyphs from a different font which causes the line heights to be different from what is expected.  I don't think we can fix this.  Instead I would use `text("\u266A")` instead of `text( "𝅘𝅥𝅮", 160, 200);`.
