### ISSUE TITLE
Add "Oh Noes Hmm" and "Oh Noes Happy" images back

### ISSUE THREAD

**Issue by darrylyeo** [Khan/live-editor#609]
Some time ago the image picker offered `getImage("ohnoes-happy")` and `getImage("ohnoes-hmm")`. It would be nice to have those back, as they broke some of my projects:
https://www.khanacademy.org/computer-programming/place-oh-noes-below-the-code-editor-proposal-illustration/5967040914522112

**Comment by kevinbarabash** [comment]
@darrylyeo this is my fault.  I added https://github.com/Khan/live-editor/blob/0c7ef693aa4ba655e9922269c80a40e0a4c0980e/build-all-images.js so that we could automatically add new images as they get added to the codebase, but it only adds images in subfolders of `images`.  `ohnoes-happy.png` and `ohnoes-hmm.png` are in `images` itself so they get skipped.

**Comment by darrylyeo** [comment]
I'd even suggest moving the images into `images/creatures` and renaming them to `OhNoes-Happy.png` and `OhNoes-Hmm.png` to be consistent with the images for Hopper's various poses.

**Comment by MattMS** [comment]
Now that #619 has been merged, can this be closed?
