### ISSUE TITLE
Creating a new live editor

### ISSUE THREAD

**Issue by K06RA** [Khan/live-editor#666]
I was wondering if it's OK for me to create a new live editor. I'm not looking for this to be implemented in the actual CS site. 

It would basically compile new JS features to ES5. It would also support p5.js since Processing.JS is dead (https://github.com/processing-js/processing-js). I'm also going to try and add multiple file support etc. 

Is that OK with you guys?

**Comment by pamelafox** [comment]
This is an open source project, so you are welcome to fork this repository. You may want to wait a few weeks, as I'm in the middle of a refactor to port from Backbone to React, bower to webpack, etc, so this repository will be more modern soon. Hopefully that makes it easier to bring in new editor languages/environments, like your plans.

**Comment by K06RA** [comment]
Awesome! I believe that this repo is based of off cloud 9's ide? (Correct me if I'm wrong). Microsoft also has their own web-based IDE called [Monaco](https://github.com/Microsoft/monaco-editor). It has intellisense and supports multiple languages. However I think that switched from Ace Editor to Monaco would take quite some time. Is there a roadmap for this project?

**Comment by frog-o** [comment]
I was also hoping to try to fork it becuase it ask me not to do "pull request" and becuase of there "cla".  I am a little worried about licensing.  Looking at the licensing file under your code it sayes it **does not** allow me to use any of the images in the advertar dir. So i would imagen i would have to delete that is that correct? 

 All I want to do is make update to your code  and share it with the community.

  I created a really simple index.html that link to demos added a run target in gulp(wich I convert to vs3) to run a html server and what to push that to my own fork but afraid to do so because of this issue.

**Comment by aparms** [comment]
I actually stopped working on this a few months ago. But you can try to add your own additions if you want!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
