### ISSUE TITLE
variables don't get reseted to undefined

### ISSUE THREAD

**Issue by Titanium-Programming** [Khan/live-editor#740]
`<!DOCTYPE html>
<html lang = "en">
    <head>
        <meta charset = "utf-8"/>
    </head>
    <body>
        <script>
            let variable; // press reload then open console
        </script>
    </body>
</html>`

**Comment by Willard21** [comment]
The actual bug here is that everything gets run twice. Quite annoying when you have a game loop, and it launches 2 game loops instead of 1.

**Comment by Titanium-Programming** [comment]
I actually never knew that but still its annoying

**Comment by Steffan153** [comment]
I think that's the reason why they only use `var`, because it would mess it up then the way things are set up. I think they have it so when you edit the code, it just replaces the `innerHTML` which is ofc much faster than to reload the entire iframe (that would defeat the point of hot reloading, lol). So it might be tricky to fix this without just removing the `live` part of the editor... :/

**Comment by Titanium-Programming** [comment]
Its the same thing with `const`  but _all_ of them are very useful.

**Comment by Willard21** [comment]
Global variables are pretty slow to access on KA, so having all your code inside a single IIFE is usually a good idea for multiple reasons, and it fixes the errors from `let` and `const`, since they become local to the closure. You also don't have to reload it normally.
```js
(function() {
const name = "Willard"
function printName() {
    console.log(name)
}
// Just put all your code in here so everything is in scope.
})()
```
There's very rarely any problems with this, and it improves performance in some cases.

> I think they have it so when you edit the code, it just replaces the innerHTML
They actually replace the entire window every time you make an edit. So globals don't persist through edits. It's just that when they're transforming your code, it gets executed twice for some reason.

**Comment by Titanium-Programming** [comment]
that kinda
